database_insertion_training_params:
  db_name: "fish_toxicity_training_db"
  table_name: "good_raw_data"
  column_names: {
    "CIC0": FLOAT(25),
    "SM1_Dz": FLOAT(25),
    "GATS1i": FLOAT(25),
    "NdsCH": FLOAT(25),
    "NdssC": FLOAT(25),
    "MLOGP": FLOAT(25),
    "LC50": FLOAT(25)
  }

data_preprocessing_training_params:
  label_column_name: LC50

model_training_params:
  linear_regression_params:
    fit_intercept: [True, False]
    copy_X: [True, False]
  random_forest_params:
    n_estimators: [10, 50, 100]
    max_features: ["sqrt", "log2"]
    max_depth: [2, 10]
    criterion: ["squared_error", "absolute_error", "friedman_mse"]
  svr_params:
    kernel: ["linear", "poly", "rbf"]
    C: [0.1, 1, 10]
  test_size: 0.2