artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://archive.ics.uci.edu/static/public/504/qsar+fish+toxicity.zip
  destination_folder: artifacts/data_ingestion/data
  filename: qsar_fish_toxicity.csv
  miscellaneous_folder: artifacts/data_ingestion/miscellaneous

data_validation_training:
  root_dir: artifacts/data_validation/training_raw_files_validated
  good_dir: artifacts/data_validation/training_raw_files_validated/good_raw
  bad_dir: artifacts/data_validation/training_raw_files_validated/bad_raw
  training_source_dir: artifacts/data_ingestion/data
  file_name: qsar_fish_toxicity.csv
  number_of_columns: 7
